import Shiboken

class GPU(Shiboken.Object):
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @staticmethod
    def available_gpu_devices(*args, **kwargs): ...
    @staticmethod
    def get_gpu_device_id(*args, **kwargs): ...
    @staticmethod
    def get_gpu_device_name_by_id(*args, **kwargs): ...
    @staticmethod
    def get_gpu_platform_id(*args, **kwargs): ...

class InterProduct(Shiboken.Object):
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @staticmethod
    def is_track_in_mocha_ae_set(*args, **kwargs): ...
    @staticmethod
    def update_track_in_mocha_ae(*args, **kwargs): ...

class Product(Shiboken.Object):
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @staticmethod
    def get_application_name(*args, **kwargs): ...
    @staticmethod
    def get_product_name(*args, **kwargs): ...
    @staticmethod
    def get_registry_application_name(*args, **kwargs): ...
    @staticmethod
    def get_registry_company_name(*args, **kwargs): ...

def get_overridden_keys(*args, **kwargs): ...
def get_setting_value(*args, **kwargs): ...
def is_gui_available(*args, **kwargs): ...
def set_setting_value(*args, **kwargs): ...
