from .project import *
from .aux_exporters import Matrix4x4 as Matrix4x4
from _typeshed import Incomplete

class SilhouetteImporter:
    def __init__(self) -> None: ...
    def add_msg(self, level, msg) -> None: ...
    def error(self, msg) -> None: ...
    def warning(self, msg) -> None: ...
    def prepare_importing(self, file_contents): ...
    def do_import(self, project: Incomplete | None = None, clip: Incomplete | None = None, view=...): ...
    @property
    def messages(self): ...
    @staticmethod
    def read_props(node): ...
