import PySide2.QtCore
from mocha.project import ChannelType as ChannelType, ImageData as ImageData, PixelFormat as PixelFormat
from typing import ClassVar

class AbstractImageIOModule(PySide2.QtCore.QObject):
    staticMetaObject: ClassVar[PySide2.QtCore.QMetaObject] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def accepts_ext(self, *args, **kwargs): ...
    def accepts_file(self, *args, **kwargs): ...
    def channel_type(self, *args, **kwargs): ...
    def get_fps(self, *args, **kwargs): ...
    def get_frame_count(self, *args, **kwargs): ...
    def get_gamma(self, *args, **kwargs): ...
    def get_interlace_mode(self, *args, **kwargs): ...
    def get_metadata(self, *args, **kwargs): ...
    def get_stream_names(self, *args, **kwargs): ...
    def image_size(self, *args, **kwargs): ...
    def load_image(self, *args, **kwargs): ...
    def pixel_format(self, *args, **kwargs): ...
    def save_image(self, *args, **kwargs): ...
    def supports_image(self, *args, **kwargs): ...
    def __delattr__(self, name): ...
    def __setattr__(self, name, value): ...
