from .project import Clip as Clip, View as View
from PySide2.QtCore import QObject
from _typeshed import Incomplete
from mocha.project import get_current_project as get_current_project

application: Incomplete

def gui_api(): ...
def down_cast_qobject(tp, obj): ...
def get_menus(): ...
def find_widget(name, convert_to_type: Incomplete | None = None): ...
def get_widgets(): ...
def swap_action_proxy(action, new_proxy): ...
def get_displayed_clip(): ...
def set_displayed_clip(clip) -> None: ...
def get_displayed_view(): ...
def set_displayed_view(view) -> None: ...
def get_current_frame(): ...
def set_current_frame(frame) -> None: ...

class ActionTriggerHandler(QObject):
    handler: Incomplete
    def __init__(self, action) -> None: ...
